import "./globals.css";
import { RecoilRoot, ThemeProvider } from "./exports";
import Sidebar from "./components/Sidebar";
import { routes } from "./routes/routes";
import Nav from "./components/Nav";
import getCurrentUser from "./helpers/getCurrentUser";
import ToastProvider from "./providers/ToastProvider";
import LoginModal from "./components/LoginModal";
import RegisterModal from "./components/RegisterModal";

export const metadata = {
	title: "SMPPS",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const currentUser = await getCurrentUser();
	return (
		<ThemeProvider>
			<RecoilRoot>
				<html lang="en">
					<body>
						<div className="min-h-screen bg-blue-gray-50/50">
							<Sidebar
								currentUser={currentUser}
								routes={routes}
							/>
							<ToastProvider />
							<LoginModal />
							<RegisterModal />
							<div className="p-4 xl:ml-80">
								<Nav currentUser={currentUser} />
								{children}
							</div>
						</div>
					</body>
				</html>
			</RecoilRoot>
		</ThemeProvider>
	);
}
